import numpy as np

ADD_ANT_EVERY = 50
INIT_X = 20
INIT_Y = 30

NEST_FACTOR = 0.1

GRID = [40, 40]
GRID_SIZE = np.prod(GRID)

FOCAL_AREA = [3, 3]
FOCAL_SIZE = np.prod(FOCAL_AREA)
ACTION_MAP = [(-1, -1), (0, -1), (1, -1), (-1, 0), (0, 0), (1, 0), (-1, 1), (0, 1), (1, 1)]
OPPOSITE_ACTIONS = list(reversed(range(len(ACTION_MAP))))

FOOD_LOCATION = [40, 5]
FOOD_SIZE = [10, 10]

WALL_LEFT = 15
WALL_RIGHT = 25
WALL_TOP = 10

NUM_PHEROMONE_LEVELS = 10
DECAY_FACTOR = 0.01

NUM_OBSERVATIONS = NUM_PHEROMONE_LEVELS
NUM_STATES = FOCAL_SIZE
NUM_ACTIONS = FOCAL_SIZE

MAX_LEN = 500
